### ISSUE TITLE
TB REM param validator incorrect

### ISSUE THREAD

**Issue by rootpd** [tomaj/php-payments#7]
The regular expression for email within REM param does not include hyphens within the email. Therefore emails such as these don't work and validator returns an exception:

- foo-bar@example.com
- newspaper-paywall@provider.net

The bug stayed hidden mostly because [CardPayAesPaymentRequest.class.php](https://github.com/tomaj/php-payments/blob/master/src/lib/TB_CardPay/CardPayAesPaymentRequest.class.php#L97) is using a condition which never validates it. See my debug output.

```php
var_dump($this->REM);
var_dump(empty($this->REM));
var_dump(!empty($this->REM));
```

```
/home/vagrant/crm/vendor/tomaj/php-payments/src/lib/TB_CardPay/CardPayAesPaymentRequest.class.php:97: string(28) "newspaper-paywall@provider.net"
/home/vagrant/crm/vendor/tomaj/php-payments/src/lib/TB_CardPay/CardPayAesPaymentRequest.class.php:99: bool(true) 
/home/vagrant/crm/vendor/tomaj/php-payments/src/lib/TB_CardPay/CardPayAesPaymentRequest.class.php:101: bool(false)
```

I'm using PHP 7.1 but I don't think it makes a difference. I stumbled upon this when trying to add REM parameter to CardPay requests, which use different kind of validation condition - calling `isempty()` helper function instead of directly calling `empty()`. Anyway, the regexp seem to be wrong in all cases not allowing usage of email with hyphens.

**Comment by tomaj** [comment]
Fixed in master
